-- V24__fix_seed_encoding.sql
-- Fix seed data corrupted at initial import (GBK client charset) - regenerate correct Chinese values.

UPDATE `sys_role` SET `role_name`='系统管理员', `remark`='管理系统所有功能，拥有全部权限' WHERE `id` = 1;
UPDATE `sys_role` SET `role_name`='总部运营', `remark`='查看全国数据，配置任务模板与动作库' WHERE `id` = 2;
UPDATE `sys_role` SET `role_name`='区域经理', `remark`='管理所辖区域门店，查看排名与抽查任务' WHERE `id` = 3;
UPDATE `sys_role` SET `role_name`='店长', `remark`='管理门店员工、审核任务、查看门店报表' WHERE `id` = 4;
UPDATE `sys_role` SET `role_name`='导购', `remark`='录入销售、执行个人任务、查看个人业绩' WHERE `id` = 5;
UPDATE `sys_permission` SET `perm_name`='仪表盘' WHERE `id` = 1;
UPDATE `sys_permission` SET `perm_name`='系统管理' WHERE `id` = 10;
UPDATE `sys_permission` SET `perm_name`='组织架构' WHERE `id` = 11;
UPDATE `sys_permission` SET `perm_name`='门店管理' WHERE `id` = 12;
UPDATE `sys_permission` SET `perm_name`='用户管理' WHERE `id` = 13;
UPDATE `sys_permission` SET `perm_name`='角色权限' WHERE `id` = 14;
UPDATE `sys_permission` SET `perm_name`='任务中心' WHERE `id` = 20;
UPDATE `sys_permission` SET `perm_name`='任务列表' WHERE `id` = 21;
UPDATE `sys_permission` SET `perm_name`='任务创建' WHERE `id` = 22;
UPDATE `sys_permission` SET `perm_name`='任务模板' WHERE `id` = 23;
UPDATE `sys_permission` SET `perm_name`='任务审核' WHERE `id` = 24;
UPDATE `sys_permission` SET `perm_name`='人效管理' WHERE `id` = 30;
UPDATE `sys_permission` SET `perm_name`='晨夕会' WHERE `id` = 31;
UPDATE `sys_permission` SET `perm_name`='员工面谈' WHERE `id` = 32;
UPDATE `sys_permission` SET `perm_name`='能力考核' WHERE `id` = 33;
UPDATE `sys_permission` SET `perm_name`='绩效复盘' WHERE `id` = 34;
UPDATE `sys_permission` SET `perm_name`='货品管理' WHERE `id` = 40;
UPDATE `sys_permission` SET `perm_name`='商品列表' WHERE `id` = 41;
UPDATE `sys_permission` SET `perm_name`='商品分类' WHERE `id` = 42;
UPDATE `sys_permission` SET `perm_name`='库存盘点' WHERE `id` = 43;
UPDATE `sys_permission` SET `perm_name`='动销分析' WHERE `id` = 44;
UPDATE `sys_permission` SET `perm_name`='场景运营' WHERE `id` = 50;
UPDATE `sys_permission` SET `perm_name`='卫生巡检' WHERE `id` = 51;
UPDATE `sys_permission` SET `perm_name`='陈列检查' WHERE `id` = 52;
UPDATE `sys_permission` SET `perm_name`='物料更新' WHERE `id` = 53;
UPDATE `sys_permission` SET `perm_name`='设备检查' WHERE `id` = 54;
UPDATE `sys_permission` SET `perm_name`='业绩数据' WHERE `id` = 60;
UPDATE `sys_permission` SET `perm_name`='销售录入' WHERE `id` = 61;
UPDATE `sys_permission` SET `perm_name`='销售报表' WHERE `id` = 62;
UPDATE `sys_permission` SET `perm_name`='报表中心' WHERE `id` = 70;
UPDATE `sys_permission` SET `perm_name`='AI 中心' WHERE `id` = 80;
UPDATE `sys_permission` SET `perm_name`='消息通知' WHERE `id` = 90;
UPDATE `sys_permission` SET `perm_name`='操作日志' WHERE `id` = 100;
UPDATE `sys_permission` SET `perm_name`='新增组织' WHERE `id` = 101;
UPDATE `sys_permission` SET `perm_name`='编辑组织' WHERE `id` = 102;
UPDATE `sys_permission` SET `perm_name`='删除组织' WHERE `id` = 103;
UPDATE `sys_permission` SET `perm_name`='新增用户' WHERE `id` = 104;
UPDATE `sys_permission` SET `perm_name`='编辑用户' WHERE `id` = 105;
UPDATE `sys_permission` SET `perm_name`='禁用用户' WHERE `id` = 106;
UPDATE `sys_permission` SET `perm_name`='重置密码' WHERE `id` = 107;
UPDATE `sys_permission` SET `perm_name`='分配权限' WHERE `id` = 108;
UPDATE `sys_permission` SET `perm_name`='批量下发' WHERE `id` = 109;
UPDATE `sys_permission` SET `perm_name`='强制任务' WHERE `id` = 110;
UPDATE `sys_permission` SET `perm_name`='审核通过' WHERE `id` = 111;
UPDATE `sys_permission` SET `perm_name`='审核驳回' WHERE `id` = 112;
UPDATE `sys_permission` SET `perm_name`='审核整改' WHERE `id` = 113;
UPDATE `sys_permission` SET `perm_name`='审核销售' WHERE `id` = 114;
UPDATE `sys_permission` SET `perm_name`='配置提示词' WHERE `id` = 115;
UPDATE `sys_permission` SET `perm_name`='组织CRUD API' WHERE `id` = 200;
UPDATE `sys_permission` SET `perm_name`='门店CRUD API' WHERE `id` = 201;
UPDATE `sys_permission` SET `perm_name`='用户CRUD API' WHERE `id` = 202;
UPDATE `sys_permission` SET `perm_name`='角色CRUD API' WHERE `id` = 203;
UPDATE `sys_permission` SET `perm_name`='任务API' WHERE `id` = 204;
UPDATE `sys_permission` SET `perm_name`='商品API' WHERE `id` = 205;
UPDATE `sys_permission` SET `perm_name`='销售API' WHERE `id` = 206;
UPDATE `sys_permission` SET `perm_name`='AI API' WHERE `id` = 207;
UPDATE `sys_permission` SET `perm_name`='报表API' WHERE `id` = 208;
UPDATE `sys_permission` SET `perm_name`='通知API' WHERE `id` = 209;
UPDATE `sys_permission` SET `perm_name`='人效API' WHERE `id` = 210;
UPDATE `sys_permission` SET `perm_name`='场景API' WHERE `id` = 211;
UPDATE `action_template` SET `action_name`='每日晨会', `description`='店长主持召开晨会，上传会议照片和纪要', `execution_standard`='拍1张会议全景照片+填写晨会纪要', `category`='晨会', `dimension`='HUMAN' WHERE `id` = 1;
UPDATE `action_template` SET `action_name`='每日夕会', `description`='店长主持当日业绩复盘夕会', `execution_standard`='上传夕会总结+当日业绩截图', `category`='夕会', `dimension`='HUMAN' WHERE `id` = 2;
UPDATE `action_template` SET `action_name`='周度员工面谈', `description`='店长与每位员工进行每周1v1面谈', `execution_standard`='填写面谈记录表+拍照确认', `category`='面谈', `dimension`='HUMAN' WHERE `id` = 3;
UPDATE `action_template` SET `action_name`='周度能力考核', `description`='店长对员工进行5项能力考核评分', `execution_standard`='按考核项逐项评分(满分100)', `category`='考核', `dimension`='HUMAN' WHERE `id` = 4;
UPDATE `action_template` SET `action_name`='月度绩效复盘', `description`='店长与员工进行月度绩效复盘并记录', `execution_standard`='填写月度复盘表(销售额/客单/品类/奖惩)', `category`='复盘', `dimension`='HUMAN' WHERE `id` = 5;
UPDATE `action_template` SET `action_name`='员工分层定级', `description`='根据业绩/服务/执行三维度定级员工', `execution_standard`='按评分规则输出 BENCHMARK/STANDARD/IMPROVING', `category`='分层', `dimension`='HUMAN' WHERE `id` = 6;
UPDATE `action_template` SET `action_name`='季度培训计划', `description`='组织门店员工进行季度产品知识/销售技巧培训', `execution_standard`='上传培训签到表+现场照片+考核成绩', `category`='培训', `dimension`='HUMAN' WHERE `id` = 7;
UPDATE `action_template` SET `action_name`='每日库存盘点', `description`='每日营业前/后盘点全部在售商品数量', `execution_standard`='扫描/核对全部商品并记录异常', `category`='盘点', `dimension`='PRODUCT' WHERE `id` = 8;
UPDATE `action_template` SET `action_name`='每周货品养护检查', `description`='每周检查贵金属/镶嵌类商品成色与完整性', `execution_standard`='逐件检查+拍照记录问题', `category`='养护', `dimension`='PRODUCT' WHERE `id` = 9;
UPDATE `action_template` SET `action_name`='周度动销分析', `description`='分析本周爆款/平销/滞销商品并制定行动方案', `execution_standard`='输出动销四象限+行动计划', `category`='分析', `dimension`='PRODUCT' WHERE `id` = 10;
UPDATE `action_template` SET `action_name`='缺货风险预警检查', `description`='检查库存低于安全库存的商品并预警', `execution_standard`='列出缺货风险清单+补货建议', `category`='预警', `dimension`='PRODUCT' WHERE `id` = 11;
UPDATE `action_template` SET `action_name`='新品推介方案', `description`='月度新品到店后制定推介与陈列计划', `execution_standard`='输出陈列方案+培训脚本+目标销量', `category`='新品', `dimension`='PRODUCT' WHERE `id` = 12;
UPDATE `action_template` SET `action_name`='促销活动筹备', `description`='大型节假日/周年庆等促销活动策划', `execution_standard`='输出活动方案(主题/商品/优惠/预热/触达)', `category`='促销', `dimension`='PRODUCT' WHERE `id` = 13;
UPDATE `action_template` SET `action_name`='高毛利主推检查', `description`='每日检查高毛利推荐商品陈列/话术执行情况', `execution_standard`='确认主推品陈列位+员工话术抽查', `category`='主推', `dimension`='PRODUCT' WHERE `id` = 14;
UPDATE `action_template` SET `action_name`='晨间卫生巡检', `description`='开店前检查店内卫生状况', `execution_standard`='逐区域检查并拍照(黄金/钻石/K金/银饰/公共区)', `category`='卫生', `dimension`='SCENE' WHERE `id` = 15;
UPDATE `action_template` SET `action_name`='午间卫生巡检', `description`='午间检查店内卫生状况', `execution_standard`='重点检查试戴区与洗手间', `category`='卫生', `dimension`='SCENE' WHERE `id` = 16;
UPDATE `action_template` SET `action_name`='晚间卫生巡检', `description`='打烊前卫生巡检与安全检查', `execution_standard`='检查电源/水源/消防/柜锁', `category`='卫生', `dimension`='SCENE' WHERE `id` = 17;
UPDATE `action_template` SET `action_name`='陈列标准检查', `description`='检查各区域陈列是否符合公司标准', `execution_standard`='按区域评分(满分100)+整改前后对比照', `category`='陈列', `dimension`='SCENE' WHERE `id` = 18;
UPDATE `action_template` SET `action_name`='C位陈列检查', `description`='重点检查C位(橱窗/入口)陈列吸引力', `execution_standard`='C位陈列标准对照+拍照', `category`='陈列', `dimension`='SCENE' WHERE `id` = 19;
UPDATE `action_template` SET `action_name`='物料更新检查', `description`='检查海报/吊旗/展架/价签等物料时效与完整', `execution_standard`='逐项检查过期/破损/缺失情况', `category`='物料', `dimension`='SCENE' WHERE `id` = 20;
UPDATE `action_template` SET `action_name`='设备运行检查', `description`='检查灯光/空调/监控/音响/POS/保险柜等设备', `execution_standard`='逐设备检查运行状态+拍照', `category`='设备', `dimension`='SCENE' WHERE `id` = 21;
UPDATE `action_template` SET `action_name`='客户体验周复盘', `description`='汇总本周客户反馈/投诉并提出改进方案', `execution_standard`='统计反馈数/投诉数+输出改进计划', `category`='体验', `dimension`='SCENE' WHERE `id` = 22;
UPDATE `action_template` SET `action_name`='门店月度综合评分', `description`='计算门店人效/货品/场景/纪律四维综合得分', `execution_standard`='按权重计算总分(35%+30%+25%+10%)', `category`='评分', `dimension`='COMPREHENSIVE' WHERE `id` = 23;
UPDATE `action_template` SET `action_name`='季度门店规划', `description`='制定下季度门店运营计划与目标', `execution_standard`='输出季度目标+行动计划+资源需求', `category`='规划', `dimension`='COMPREHENSIVE' WHERE `id` = 24;
UPDATE `action_template` SET `action_name`='节假日特别巡检', `description`='国庆/春节/情人节等节日特殊检查', `execution_standard`='卫生+陈列+物料+安全全面检查', `category`='节日', `dimension`='COMPREHENSIVE' WHERE `id` = 25;
UPDATE `action_template` SET `action_name`='异常事件上报', `description`='门店异常事件(客户投诉/商品遗失/安全事故等)', `execution_standard`='描述事件+拍照证据+处理措施', `category`='异常', `dimension`='COMPREHENSIVE' WHERE `id` = 26;
UPDATE `action_template` SET `action_name`='店长交接班检查', `description`='店长换班时进行全面交接检查', `execution_standard`='卫生/商品/现金/设备/异常事项逐项确认', `category`='交班', `dimension`='COMPREHENSIVE' WHERE `id` = 27;
UPDATE `sys_user` SET `real_name`='系统管理员' WHERE `id` = 1;

